### ISSUE TITLE
Show absolute speedometer values

### ISSUE THREAD

**Issue by stuartphilp** [mozilla/firefox-health-dashboard#21]
Possibly show:

Speedometer v2 Chrome absolute value - label “Chrome” color:red?
Speedometer v2 Firefox Nightly absolute value - label “Nightly” color: orange?
Speedometer v2 Chrome*.8 value - label “Target 57” color: grey?
Speedometer v2 Chrome*.9 value - label “Target 60” color: green?

**Comment by stuartphilp** [comment]
Something along the lines of <img width="594" alt="screen shot 2017-10-31 at 11 45 40 am" src="https://user-images.githubusercontent.com/2964961/32233593-1cab3c1e-be31-11e7-96a1-01a1cc8001b8.png">

**Comment by armenzg** [comment]
Do you want to get rid completely of what there is there already?
Or add one more graph?

I currently see 4 graphs with these configurations:

- 32-bit nightly vs Canary
- 64-bit nightly vs Canary
- 32-bit beta vs Canary
- 64-bit beta vs Canary

What are the differences between Chrome, Chrome .8 & Chrome .9?
If you want different versions besides Canary to be tested we will need to add more configurations to the AWFY set up and that could take some time.

What do you mean about Target 57 & Target 60?

**Comment by armenzg** [comment]
I evaluated the code and data transformations and this should take from few days to max 2 weeks.
My assumption is that for each comparative table we will have another one just below to show the absolute values (rather than have both data sets within the same graph: comparison & absolutes).
This perhaps is not difficult but I would have to investigate how well it will work (left Y axis for percentage values while right Y axis for absolute scores).

As we spoke over our call I can get my feet wet with mission-control and then jump on this on the week of the 27th.

I will, however, need an answer to the questions above. Thanks.

**Comment by stuartphilp** [comment]
This would replace each of the 4 (still need the channel and architecture comparisons). 

.8 and .9 are calculations of thresholds that we want to cross, so 80% and 90% of chromes actual score. 

Target 57/60 are the Firefox releases where we want to cross the 80% and 90% thresholds. So since 57 has shipped (still display it), we want to target 90% by 60.

Let me know if there are other questions!

**Comment by armenzg** [comment]
I believe what you want is to replace the 4 graphs with 4 graphs (ignore Talos speedometer), however, instead of showing percentages and a 20% band you want to see:
    * The current score of Nightly
    * The current score of Chrome Canary
    * The 80% score - named Target 57
    * The 90% score - named Target 60

I assume that Nightly will target 80% of the score (green status depends on it) for the current version (59) and once we get to 60 we target 90% (green status depends on it).

I assume that Beta will target 80% of the score (green status depends on it) during the current version (58) and the following (59) and once we get to 60 we target 90% (green status depends on it).

If I misunderstood this we can chat on our 1x1 on Wednesday.

**Comment by armenzg** [comment]
Speedometer data has a higher density of data points for the last 3 days and that can be seen on the graphs I'm plotting.
![image](https://user-images.githubusercontent.com/44410/33786877-d9270628-dc38-11e7-953b-000f7fe1c235.png)
![image](https://user-images.githubusercontent.com/44410/33786905-f028b592-dc38-11e7-8130-f533384117e4.png)

What do you want me to do about it? Leave it as is? Smooth it?

I'm auto-deploying my branch here:
https://health-quantum-dashboard.herokuapp.com/quantum

This is WIP:
https://github.com/mozilla/platform-health/compare/master...armenzg:speedometer

I'm done a refactoring on how we manipulate speedometer data. Instead of using indexes of an array we actually use

Next, I will add a line equivalent to Chrome's, however, it will be 80% of all of its values.

![image](https://user-images.githubusercontent.com/44410/33786480-57e75b40-dc37-11e7-9260-7c760bffe25f.png)

**Comment by stuartphilp** [comment]
@armenzg Leave it as is, we like to see the actual changes as opposed to smoothed/averaged numbers. Can you make it show the score rather than the time btw? We've decided to use the score for 2018. Looking forward to seeing the 80% and 90% markers, but looks great so far!

**Comment by armenzg** [comment]
It should be possible.
This is the data of the benchmark "misc-score":
https://arewefastyet.com/data.php?file=bk-aggregate-speedometer-misc-score-36.json

WRT to the comparison graphs (the ones in use), from the title of the issue I understand that you want to keep them. Are we to change it to use the score or keep the time?

**Comment by stuartphilp** [comment]
I think we can actually replace those entirely with these, it will show the same basic data

**Comment by armenzg** [comment]
I have managed to use Widget with MetricsGraphics by allowing Widget to have children instead of only work with an svg. See [the changes required](https://github.com/armenzg/platform-health/compare/react-metrics-graphics...armenzg:criteria). This allows us to use composition.

Unfortunately, this is not building well in production [1]. Reproducible locally with `yarn build:prod`.
This is related to including react-metrics-graphics as a dependency.

@wlach @eliperelman any suggestions?

I'm thinking of switching to neutrino if this is all side effects of the handcrafted webpack config.

For what is worth, `yarn build:dev` does not have any issues.

Steps to reproduce:

> git checkout -b armenzg-criteria master
> git pull https://github.com/armenzg/platform-health.git criteria
> yarn build:prod

[1]
> ERROR in app.1683db.js from UglifyJs
> Unexpected token: name (l) [../node_modules/react-metrics-graphics/build/MetricsGraphics.js:1,2669][app.1683db.js:106701,2637]
> Child html-webpack-plugin for "index.html":
>      1 asset
>        [0] ../node_modules/html-webpack-plugin/lib/loader.js!./index.html 689 bytes {0} [built]
>         + 3 hidden modules
> error Command failed with exit code 2.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by armenzg** [comment]
I forgot to mention.
Here's a screenshot with partially working "release criteria" widget:
![image](https://user-images.githubusercontent.com/44410/34263183-9d507676-e63c-11e7-8126-7ad4753d1f83.png)

**Comment by armenzg** [comment]
I've decided to modernize platform-health to make it easier to maintain.

I hope it will reduce discrepancies between production and development as well as making it easier to add newer packages.

**Comment by armenzg** [comment]
I've managed to set up review apps correctly.
We have the frontend being deployed here:
https://platform-health-pr-35.herokuapp.com/quantum
It queries this backend:
https://firefox-health-backend-pr-5.herokuapp.com

I've noticed that the y-axis are inverted between AWFY and this.
In AWFY we're using *higher* is faster.
What is the preference? (see screenshot)

https://cl.ly/3S3v3T2M1s2x
![image](https://user-images.githubusercontent.com/44410/35990483-229a0c32-0cd2-11e8-94cd-229a1cc3e7c0.png)

**Comment by armenzg** [comment]
@stuartphilp r? wrt to previous comment.

The criteria widget now works. You can test it live here:
https://platform-health-pr-35.herokuapp.com/quantum

I'm thinking of making the target line to be a dotted gray line. What do you think?

You can see a screenshot in here:
![image](https://user-images.githubusercontent.com/44410/36002801-79f97d9c-0cf9-11e8-978d-f9f2a7406220.png)

**Comment by armenzg** [comment]
The changes seem to be live.
@stuartphilp I've addressed the issues you pointed out yesterday.

Here's a screenshot of what it looks like:
![image](https://user-images.githubusercontent.com/44410/36269716-dcb38c2c-1247-11e8-8982-86756b70779c.png)
