### ISSUE TITLE
Quantum Flow profiling graph

### ISSUE THREAD

**Issue by stuartphilp** [mozilla/firefox-health-dashboard#22]
Within bugzilla we are now tracking [qf:needs-analysis] and [qf:analyzed] whiteboard tags, this will be a top line goal for 2018 to keep performance issues well triaged. 

We need to create a graph showing two lines over time indicating the NeedsAnalsyis:Analyzed ratio of profiling bugs

**Comment by armenzg** [comment]
Do these whiteboard tags exist?

I tried searching for them:
https://bugzilla.mozilla.org/buglist.cgi?list_id=14020499&resolution=---&status_whiteboard_type=allwordssubstr&query_format=advanced&status_whiteboard=%5Bqf%3Aneeds-analysis%5D

https://bugzilla.mozilla.org/buglist.cgi?list_id=14020499&resolution=---&status_whiteboard_type=allwordssubstr&query_format=advanced&status_whiteboard=[qf%3Aanalyzed]

**Comment by armenzg** [comment]
I believe what is involved here is something around uncommenting this:
https://github.com/mozilla/firefox-health-dashboard/blob/master/src/quantum/index.js#L146
and make changes in here:
https://github.com/mozilla/firefox-health-dashboard/blob/master/src/quantum/flow.js

Perhaps a good opportunity is to allow it to receive whiteboard tags as props.

**Comment by sarah-clements** [comment]
A few questions/comments about this project: 

1) The current endpoint the Flow component is using (/api/bz/burnup) uses a whiteboard tag of [qf:p1] and divides the bugs into a count of total bugs and bugs closed, by date. @stuartphilp Does any of this make sense to use for this project?

2) A preliminary pull of the bugzilla API only returned one result with the [qf:needs-analysis] tag and none with the [qf:analyzed] tag. Also, this endpoint might need to make two separate calls for bugzilla to each since it appears that combining those tags into one request returns nothing (so the bugzilla endpoint/database must be treating them as 'and' rather than 'or' parameters).

**Comment by stuartphilp** [comment]
@sarah-clements Going forward the quantum releases will be every 3rd Firefox release, so Firefox 61, 64, 67, etc. The new whiteboard tags are ```[qf:p1][qf:f61]```, where [qf:p1] means it's top priority, and [qf:f61] is targeting Firefox 61 release. 

We will need to update this to [qf:f64] once 61 ships.

The [qf:needs-analysis] tag is supposed to be used, but the dev work is just kicking off so I expect more activity soon.

**Comment by klahnakoski** [comment]
Please note that the Bugzilla-ETL cluster also has this information for all bugs, over all time.  This is in the form of numerous bug snapshots, each marked with the range of time they are valid.  A single query, grouped by day can provide you with timeseries data over any range, and any resolution.

https://wiki.mozilla.org/BMO/ElasticSearch
