### ISSUE TITLE
Redirect https://health.graphics/quantum

### ISSUE THREAD

**Issue by stuartphilp** [mozilla/firefox-health-dashboard#84]
A lot of people have https://health.graphics/quantum saved as the URL they go to, but with the 64/32 bit split this link no longer works. We should either redirect this to https://health.graphics/ or even better a smaller version of that home page that just shows the 32 and 64 bit links.

**Comment by sarah-clements** [comment]
Per our convo in the channel on Monday, it seemed like a good idea to add an info icon to explain changes in quantum routes. However, I think it would make more sense to have a menu in place that allows people to navigate directly to /responsiveness/parent and other routes, without requiring them to only do so via the address bar. I'm only pushing the redirect for now as @armenzg might want to weigh in on this too.

**Comment by armenzg** [comment]
It seems you landed code to accomplish the redirect requested in this issue, thus, I will close the issue.

We can file an issue to reach addresses that are not currently linked from the Home page.
Eli recommends material design instead of react-strap:
https://material.io/components/web/
Code examples can be found here:
https://github.com/taskcluster/taskcluster-web
